cwlVersion: v1.2
class: FEMTask

id: dicom-file-integrity-checker
label: DICOM File Integrity Checker
doc: >-
  Validates DICOM dataset integrity and sequence consistency, producing
  machine-readable QA reports for federated execution.

requirements:
  - class: DockerRequirement
    dockerPull: harbor.eucaim.cancerimage.eu/processing-tools/dicom_file_integrity_checker:latest

  - class: EnvVarRequirement
    envDef:
      - envName: FEM
        envValue: "true"

  - class: ResourceRequirement
    coresMin: 2
    ramMin: 4096

baseCommand: [/app/entrypoint.sh]

inputs:
  input_directory:
    type: string
    doc: Fixed input folder name inside /input used by the container.
    required: true
    default: imaging_data
    hidden: true
    source: user

  config_string:
    type: string
    doc: >-
      Optional QA configuration as Python-dict string under root key 'QA'.
      If you provide 'input_directory', it must match the hidden fixed
      input_directory value ('imaging_data') used by the runtime layout.
      Include 'catalogue_file' inside the mounted /config or /output (where the user has written permissions) so the Python script can resolve it.
      Example: {'QA': {'catalogue_file': 'catalogue.xlsx', 'sequence_selection': ['ALL'], 'modality_selection': ['ALL'], 'input_directory': 'imaging_data'}}
    required: false
    default: null
    hidden: false
    source: user
    inputBinding:
      position: 1
      prefix: --config-string
      separate: true

outputs:
  reports_artifacts:
    type: Directory
    doc: >-
      Complete reports and logs tree generated by the checker, including xlsx,
      json, html reports and debug logs, but excluding the processed DICOM
      output tree.
    outputBinding:
      glob: reports_dicom_file_integrity_checker

expectedExitCode: 0

metadata:
  author: GIBI230 / IIS La Fe
  version: "2.1.3"
  orchestrator:
    network: overlay
    additional_metadata:
      fem_mode_forced: true
      notes: "FEM=true disables interactive license prompt. Runtime/deployment must provide /input, /output and /config mounts."
