cwlVersion: v1.2
class: FEMTask

id: time-coherence-tool
label: Time Coherence Tool

doc: >-
  Generates interactive medical timelines from patient data in Excel or CSV format,
  validates temporal coherence, and produces SVG, PNG and PDF outputs for
  federated execution environments.

requirements:
  - class: DockerRequirement
    dockerPull: harbor.eucaim.cancerimage.eu/processing-tools/time_coherence_tool:1.1.0

  - class: ResourceRequirement
    coresMin: 2
    ramMin: 4096

baseCommand: [/app/entrypoint.sh]

inputs:
  data_file_path:
    type: string
    doc: >-
      Full path to input data file. Can be /input/file.xlsx, /output/file.csv, etc.
      Supports .xlsx, .xls, and .csv formats.
    required: false
    default: null
    hidden: false
    source: user
    inputBinding:
      position: 1
      prefix: --data-file-path
      separate: true

  data_file:
    type: string
    doc: >-
      Legacy option - filename only, assumes /input/ directory.
    required: false
    default: 'data_source.xlsx'
    hidden: false
    source: user
    inputBinding:
      position: 2
      prefix: --data-file
      separate: true

  img_config_file:
    type: string
    doc: >-
      Icon mapping configuration file.
    required: false
    default: 'image_configuration.xlsx'
    hidden: false
    source: user
    inputBinding:
      position: 3
      prefix: --img-config-file
      separate: true

  label_config_file:
    type: string
    doc: >-
      Display label mapping file.
    required: false
    default: 'label_configuration.xlsx'
    hidden: false
    source: user
    inputBinding:
      position: 4
      prefix: --label-config-file
      separate: true

  event_config_file:
    type: string
    doc: >-
      Event positioning configuration.
    required: false
    default: 'event_configuration.xlsx'
    hidden: false
    source: user
    inputBinding:
      position: 5
      prefix: --event-config-file
      separate: true

  rules_config_file:
    type: string
    doc: >-
      Validation rules file.
    required: false
    default: 'rules_configuration.xlsx'
    hidden: false
    source: user
    inputBinding:
      position: 6
      prefix: --rules-config-file
      separate: true

  generate_svg:
    type: string
    doc: >-
      Generate SVG output (true/false).
    required: false
    default: 'true'
    hidden: false
    source: user
    inputBinding:
      position: 7
      prefix: --generate-svg
      separate: true

  generate_png:
    type: string
    doc: >-
      Generate PNG output (true/false).
    required: false
    default: 'true'
    hidden: false
    source: user
    inputBinding:
      position: 8
      prefix: --generate-png
      separate: true

  generate_pdf:
    type: string
    doc: >-
      Generate PDF output (true/false).
    required: false
    default: 'true'
    hidden: false
    source: user
    inputBinding:
      position: 9
      prefix: --generate-pdf
      separate: true

  png_dpi:
    type: int
    doc: >-
      PNG resolution in DPI.
    required: false
    default: 2000
    hidden: false
    source: user
    inputBinding:
      position: 10
      prefix: --png-dpi
      separate: true

  timeline_width:
    type: int
    doc: >-
      Timeline width in pixels.
    required: false
    default: 700
    hidden: false
    source: user
    inputBinding:
      position: 11
      prefix: --timeline-width
      separate: true

outputs:
  timeline_outputs:
    type: Directory
    doc: >-
      Main output tree generated by the tool, including svg, png, pdf, config
      and icons folders under the mounted /output directory.
    outputBinding:
      glob: /output

expectedExitCode: 0

metadata:
  author: GIBI230 / IIS La Fe
  version: "1.1.0"
  orchestrator:
    network: overlay
    additional_metadata:
      fem_mode_forced: true
      notes: >-
        Runtime/deployment must provide /input and /output mounts. The tool
        writes its main results into /output and can optionally run demo data
        with --test.
